# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='t_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('userAlias', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=128)),
            ],
        ),
    ]
