# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='userType',
            field=models.IntegerField(default=0),
        ),
    ]
